version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_PUBLIC_WS_URL=ws://backend:8080
    depends_on:
      - backend
    networks:
      - youcreator-network

  # 后端服务
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=youcreator
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=youcreator
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENSEARCH_URL=http://opensearch:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=admin
      - AI_SERVICE_URL=http://ai-service:8000
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mysql
      - mongodb
      - redis
      - opensearch
      - ai-service
    networks:
      - youcreator-network

  # AI服务
  ai-service:
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - REDIS_URL=redis://redis:6379
    volumes:
      - ai-models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - redis
    networks:
      - youcreator-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=youcreator
      - MYSQL_USER=youcreator
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ../database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - youcreator-network

  # MongoDB数据库
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=youcreator
    volumes:
      - mongodb-data:/data/db
      - ../database/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - youcreator-network

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - cluster.name=youcreator-cluster
      - node.name=youcreator-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - youcreator-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - youcreator-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - youcreator-network

volumes:
  mysql-data:
  mongodb-data:
  opensearch-data:
  redis-data:
  ai-models:

networks:
  youcreator-network:
    driver: bridge
